spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/cookbook
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
